### ISSUE TITLE
Exception when starting the app

### ISSUE THREAD

**Issue by mateusgrb** [travelbank/Knit#48]
The app doesn't crash but it throws this exception and remains stuck on the splash screen forever.

> Process: com.myapp.app.preview, PID: 22256
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.app.preview/com.myapp.support.pages.home.StartActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.myapp.knit.KnitPresenter.getView(KnitPresenter.java:74)
        at com.myapp.support.pages.home.StartActivityPresenter.navigateToIntroActivity(StartActivityPresenter.java:47)
        at com.myapp.support.pages.home.StartActivityPresenter.onViewStart(StartActivityPresenter.java:23)
        at com.myapp.support.pages.home.StartActivityPresenter_Exposer.use_onViewStart(StartActivityPresenter_Exposer.java:54)
        at com.myapp.support.pages.home.StartActivityPresenter_Presenter.onViewStart(StartActivityPresenter_Presenter.java:135)
        at com.myapp.knit.KnitAppListener.onActivityStarted(KnitAppListener.java:75)
        at android.app.Application.dispatchActivityStarted(Application.java:207)
        at android.app.Activity.onStart(Activity.java:1245)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:564)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at com.myapp.support.utilities.AppAgnosticBaseActivity.onStart(AppAgnosticBaseActivity.java:114)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
        at android.app.Activity.performStart(Activity.java:7029)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

Reproduced on a Nexus 6P Android 8.1 and on an emulator. Don't think it's device specific though.

**Comment by OmerUygurOzer** [comment]
on it.
